### ISSUE TITLE
OpenAPI visual documentation is missing for verb/nouns

### ISSUE THREAD

**Issue by tpavesi** [app-generator/flask-soft-ui-dashboard#2]
Hello,
I am looking at http://127.0.0.1/api where the visual documentation for the API is shown. Great that Open API has been implemented, but the documentation parameters are missing. This makes it a lot harder to work with it. Although I have to redesign the API nouns, it would help less experienced users to understand the API model and how to send the GET/POST JSON fields.

Also, the authorisation is missing from the schema. I can see the token on the user profile, but token authentication is not in the API doc (as seen on the Pet Store example -- AUTHORISE).

**What I can see from SOFTUI:**
![soft_ui_api](https://user-images.githubusercontent.com/3018008/194007553-bfe009d1-bf1e-466c-a87a-f4e2e4d9c9d3.png)

**What I wish to see (using openAPI PetStore Demo):**
![openapi_demo_parameters](https://user-images.githubusercontent.com/3018008/194007870-4b3a5c24-6745-45e0-8646-dcf44e580adf.png)

**AUTHORISE**
![openapi_authorise](https://user-images.githubusercontent.com/3018008/194008708-aa765da5-1e7a-4554-ae64-151ae182e200.png)

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
