### ISSUE TITLE
Missing Authentication verification for some Blueprint routes

### ISSUE THREAD

**Issue by tpavesi** [app-generator/flask-soft-ui-dashboard#3]
Hello,
Some blueprint routes are missing the @login_required to prevent a user from manually placing a URL and accessing the page without proper authentication. Please confirm as I am getting error _**AttributeError: 'AnonymousUserMixin' object has no attribute 'role'**_

app\authentication\routes.py
@blueprint.route('/profile', methods=['GET', 'PUT'])
@blueprint.route('/user_list', methods=['GET'])
@blueprint.route('/update_status', methods=['PUT'])
@blueprint.route('/delete_user', methods=['DELETE'])      
@blueprint.route('/confirm/<token>')
@blueprint.route('/change_password', methods=['POST'])   

Thank you.

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
