### ISSUE TITLE
Error Pages (page-403.html) - Missing action/URL on GO TO HOME button

### ISSUE THREAD

**Issue by tpavesi** [app-generator/flask-soft-ui-dashboard#4]
This is for FLASK SOFT UI DASHBOARD PRO 1.0.6

**ISSUE:**
The [GO TO HOME] button is missing the URL or action to go to the website's homepage.

**Reproduce:**
1. Open website http://127.0.0.1:5000/page-403.html
2. Click on the [GO TO HOME] Button

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
