### ISSUE TITLE
User List/My profile Missing side menu to show as selected

### ISSUE THREAD

**Issue by tpavesi** [app-generator/flask-soft-ui-dashboard#6]
**ISSUE**
When clicking on the sidenav for my profile or user list menu items, the segment is not being sent. This causes the icon not to change to an active status (and show as selected).

**REPLICATE**
1. navigate to My profile - http://127.0.0.1:5000/profile or
2. Navigate to Users - http://127.0.0.1:5000/user_list
3. SideNav icons do not show as selected.

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
